apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: podstail
spec:
  platforms:
  - sha256: 9763479d86577f30a20cac00378ff57b9a41ff212371db517589753f2e29c44b
    uri: https://github.com/ajitchahal/kubectl-plugins/raw/master/plugins.tar.gz
    files:
    - from: ""
      to: "."
    bin: podstail.sh
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [darwin, linux]}
  version: "v0.1.0"
  homepage: https://github.com/ajitchahal/kubectl-plugins
  shortDescription: Tail logs from multiple pods matching label selector, namespace and container.
  caveats: |
    Examples
    $ kubectl plugin mtail app=web,tier=frontend
    $ kubectl plugin mtail app=web,tier=frontend -n my-namespace my-container